# VSCode Rest Client extension will display `Send Request` button below to
# perform integration test when running emulators locally

POST http://127.0.0.1:5001/test/us-central1/groupJoin
Content-Type: application/json

{
  "parent_group_id": "test",
  "parent_name": "secret",
  "parent_text_id":""
}